### ISSUE TITLE
Decision on publication_datetime on cached data

### ISSUE THREAD

**Issue by kaiwirt** [wmo-im/wis2-notification-message#10]
What is the expected behaviour of publication_datetime on messages from the cache?

- Keep original value (would allow to determine round-trip time)
- Replace with the time when the message was (re-(published by the cache

**Comment by josusky** [comment]
I would prefer to keep the original. I think that measuring the round-trip (distribution/delivery delay) is the best use case for it.

**Comment by antje-s** [comment]
There are reasons for both, but for me the total time delay is also an important aspect and original pubtime is therefore good

**Comment by kaiwirt** [comment]
The current implementation at GC Offenbach is keep the original

**Comment by kaiwirt** [comment]
If this is accepted by all i would suggest to close this as decided
