### ISSUE TITLE
clarify version property fixed value

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-notification-message#100]
FYI `version` is currently fixed to `v04` in the [schema](https://github.com/wmo-im/wis2-notification-message/blob/main/schemas/notificationMessageGeoJSON.yaml#L15) as well as [requirements](https://github.com/wmo-im/wis2-notification-message/blob/main/standard/requirements/core/REQ_version.adoc).

Now that WNM will be published as `1.0`, we should should consider updating `version` to `1.0` as well, before initial publication.

**Comment by josusky** [comment]
Well, `v04` in WNM is almost as arbitrary as `a` in WTH. (greetings to @6a6d74)
That is, it would be nice to change it to a less arbitrary/obscure value, but is it worth the effort?

**Comment by josusky** [comment]
Options on further steps:
1. We could use this as an exercise on how to manage WNM version changes - or breaking changes in general.
2. Close both eyes, ask all participants of the pre-operational phase to adjust their subscribers to accept both `v04` and `1.0` as equivalents, ask publishers to start using `1.0` (perhaps with a few days delay) and ... apologise everyone for the inconvenience.

**Comment by golfvert** [comment]
Considering how the (reasonably) simple change from country/centre-id to country-centre-id is really slowly happening, I wouldn't add yet another change in the mix. Let's consider v04 as a tribute to the ancestors of WIS2 in Canada :)

**Comment by tomkralidis** [comment]
Suggest we use/align the OGC/WCMP2 approach of conformance, with the following:

- deprecate "v04"
- add:
```json
"conformsTo": [
  "http://wis.wmo.int/spec/wnm/1/conf/core"
]
```

**Comment by josusky** [comment]
I like it. It offers a a way how to "migrate" painlessly. 
Just to avoid confusion, what @tomkralidis suggests is it to deprecate `version` property in WNM, not its actual value. It will be keep it in for a while, to ensure compatibility, and gradually replaced by a new property `conformsTo`.

**Comment by golfvert** [comment]
Yes. When checking the conformity of a message "Version" will be accepted for "some" time. And when in there "v04" it is.

**Comment by tomkralidis** [comment]
A PR is put forth in #105, for discussion at the next TT-WISMD meeting.

**Comment by amilan17** [comment]
FT2024-2?
