### ISSUE TITLE
Harmonization of Documents

### ISSUE THREAD

**Issue by antje-s** [wmo-im/wis2-notification-message#108]
In WIS-Manual Appendix E (WIS2 Notification Message) under 1.15 Links REQ10 D FTP/SFTP is also permitted as a protocol 
("The links shall be HTTP, HTTPS, FTP or SFTP.") but in WIS-Guide under 2.5.2 Download protocol (HTTP) only HTTP is allowed for downloads "The HTTP protocol (RFC 7231 ) is to be used for all WIS2 download workflow.". So at least for "canonical", "update" and "deletion" we should also restrict the protocol to HTTP/HTTPS so that both documents are synchronized.

**Comment by tomkralidis** [comment]
TT-WISMD 2024-03-25
- links with type `canonical`/`update`/`deletion` should ONLY be HTTP (protocol); HTTPS continues to be preferred
- SFTP is still used in some organizations
- we should review the Manual

ACTIONS:
- @amilan17 to review Manual regarding provision of protocols

**Comment by amilan17** [comment]
From what I can tell, all of the statements in the WIS2 Manual refer to the WIS2 Guide for details.
