### ISSUE TITLE
add requirement for metadata deletion

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-notification-message#114]
As discussed at the WIS2 Global Services Testing meetings (2024-05-24), a WCMP2 deletion requires `properties.metadata_id` to exist so that a GDC can delete accordingly.

This means we need to add a Requirement that if a WNM is a WCMP2 deletion, then `properties.metadata_id` is required.

Note that `properties.metadata_id` will be a required property of WNM (which will solve/fix the above), but it is unclear on when this will be put forth.

**Comment by antje-s** [comment]
Sounds like a good idea, the check should be included in the GB within the message validation.

**Comment by tomkralidis** [comment]
For example, message to `origin/a/wis2/+/metadata/#`:

```json
{
    "id": "31e9d66a-cd83-4174-9429-b932f1abcdef",
    "conformsTo": [
        "http://wis.wmo.int/spec/wnm/1/conf/core"
    ],
    "type": "Feature",
    "geometry": null,
    "properties": {
        "pubtime": "2022-12-22T16:40:37Z",
        "datetime": "2022-11-11T11:11:11Z",
        "data_id": "data/data-123/items/abcdefab-abcd-1234-5678-0123456789ab",
        "metadata_id": "urn:wmo:md:test-nmhs-xyz:some_dataset"
    },
    "links": [
        {
            "href": "https://example.org/92c557ef-d28e-4713-91af-2e2e7be6f8ab.txt",
            "rel": "deletion"
        }
    ]
}
```

### Proposal

- for metadata subscription, in WNM link objects with `rel=deletion`, then `properties.metadata_id` is required
- target is FT 2024-02

ACTION: @tomkralidis to issue associated PR
