### ISSUE TITLE
Add field indicating access permissions

### ISSUE THREAD

**Issue by kaiwirt** [wmo-im/wis2-notification-message#12]
The manual on WIS2 states that
3.6.2.3 	A WIS node may restrict access to its core data, relying on Global Caches providing access to data consumers.

If a client is subscribing to origin/# the download of data form that client would fail. Thus a field in the message should be available indicating the access permissions in some way. Maybe also the authentication method (token, user/passwd, certificate) would be useful

Note that this is different than the core / recommended meaning in the topic hierarchy

**Comment by tomkralidis** [comment]
WCMP2 addresses this by reusing the [OpenAPI Security scheme model](https://spec.openapis.org/oas/v3.0.3#security-scheme-object) as part of a link object.  Example:

```json
"links": [{
  "rel": "download",
  "type": "application/json",
  "title": "link to WAF endpoint",
  "href": "https://example.org/data/secure-data",
  "security": {
    "type": "http",
    "scheme": "basic",
    "description": "Please contact the data provider for accessing this secured resource."
  }
}]
```

Thus we can leverage in the same way in WNM.  Thoughts @kaiwirt @josusky @antje-s @McDonald-Ian @ktsuboi-jma @davidpodeur ?

**Comment by josusky** [comment]
I think that this information is needed once, that is when you discover a new data set and want to start accessing it. Once you get through this initial step you will never more need to check it again. So keeping it only in the metadata record (WCMP2) seems appropriate to me.

**Comment by tomkralidis** [comment]
Good point.  The WNM can then encode `properties.metadata_id` to allow a notification subscriber to walk back to the associated WCMP2 record.  I'll PR a minor editorial update to section [7.1.7.3](https://wmo-im.github.io/wis2-notification-message/standard/wis2-notification-message-DRAFT.html#metadata_id) to this effect.

**Comment by tomkralidis** [comment]
PR in #49
