### ISSUE TITLE
per_core_metadata_id bugs

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-notification-message#128]
per_core_metadata_id is not included and has Recommendation label

![image](https://github.com/user-attachments/assets/094d518e-7d62-4198-94c7-50ffe9f3c011)

![image](https://github.com/user-attachments/assets/a6d58442-b882-4ba5-a01e-dd763fa611fd)

**Comment by tomkralidis** [comment]
PR in #130

**Comment by amilan17** [comment]
I think we can consider this as editorial -- not for ft amendments.
