### ISSUE TITLE
Approve changes to WTH (domain aspects) ahead of Global Services testing

### ISSUE THREAD

**Issue by golfvert** [wmo-im/wis2-notification-message#133]
The changes to WTH are approved through FT. So, for FT-2 end of 2024. 
It would be better to have them approved ahead of the Global Services testing early October. As we are still in pre-op mode, it is acceptable, I think. We have pending changes for Ocean, Climate, Space Weather...

**Comment by amilan17** [comment]
@golfvert the proposals for WTH topics will be circulated to NFPs soon, but according to the fast-track procedure they have 2 months to respond. So at a  minimum, if we follow the FT procedure, these will not be WMO approved until after mid-October/early November at the earliest.

**Comment by golfvert** [comment]
This is why I am suggesting to skip this validation as we are still in pre-op mode.
Or to do it in parallel, at least.

**Comment by amilan17** [comment]
@golfvert Can you please elaborate on which validation?

**Comment by golfvert** [comment]
Sending to NFP is the "validation".

**Comment by tomkralidis** [comment]
I think this issue belongs in WTH proper?

**Comment by golfvert** [comment]
During the tests, we used the (future) new Topic Hierarchy...
Issue can be closed.
