### ISSUE TITLE
YAML schema def and security object in repository and pages is different from that published on schemas.wmo.int

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/wis2-notification-message#135]
As per title, the definition of the security object from the links is not consistent between the yaml and JSON versions.

https://github.com/wmo-im/wis2-notification-message/blob/822e61934f409dda6269eea8c150fdf4b87d947a/schemas/notificationMessageGeoJSON.yaml#L149-L151

is not consistent with:

```json
"properties": {
                            "security": {
                                "type": "object",
                                "patternProperties": {
                                    "^[a-zA-Z0-9\\.\\-_]+$": {
                                        "oneOf": [
                                            {
                                                "$ref": "#/definitions/Schema_Reference"
                                            },
                                            {
                                                "$ref": "#/definitions/Schema_SecurityScheme"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
```

from: https://[schemas.wmo.int/wnm/1.0.0/schemas/wis2-notification-message-bundled.json](https://schemas.wmo.int/wnm/1.0.0/schemas/wis2-notification-message-bundled.json)

**Comment by tomkralidis** [comment]
@david-i-berry:

- the YAML schema is the base schema which includes references to OGC and OpenAPI schema definitions/building blocks
- the JSON schemas are generated from the YAML schema and fully dereferenced.  This is documented at https://github.com/wmo-im/wis2-notification-message/tree/main/schemas
- the JSON schemas are normative, with no external references, in support of runtime validation (with no external dereferencing)

**Comment by david-i-berry** [comment]
OK, I see my error - I was jumping to the wrong definition when I was checking, checking against `securityScheme` vs `Components.properties.securitySchemes`
