### ISSUE TITLE
make clear that version and conformance are mutually exclusive during the deprecation period for version

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-notification-message#140]
Given the implementation of #100, add a note explicitly stating that only one of `conformsTo` or `version` (deprecated) should be used during the deprecation period, and not both.

cc @golfvert

**Comment by golfvert** [comment]
I agree. Especially considering that the schema validation will fail when both are in the WNM.

**Comment by amilan17** [comment]
FT2025-1?

**Comment by tomkralidis** [comment]
Yes.

**Comment by amilan17** [comment]
add to FT2024-2 milestone as an additional revision received during NFP period of review.
