### ISSUE TITLE
Clarification on Date / Time Formats

### ISSUE THREAD

**Issue by kaiwirt** [wmo-im/wis2-notification-message#2]
If i am not mistaken, the Date / Time Formats of the examples are not RFC 3339 Compliant.

Example: 20220320T045018.314854383Z
Example from RFC 3339: 1985-04-12T23:20:50.52Z

According to RFC 3339 a date is defined as
date-fullyear "-" date-month "-" date-mday

**Comment by petersilva** [comment]
What part of RFC3339 are you referring to?  Everywhere I see "-" it is enclosed in [] which means it is  optional.  For example: on page 12 of RFC 3339, I see:
```
 datespec-full     = datepart-fullyear date-month ["-"] date-mday

```
to parse RFC3339 dates, you need to consider the - optional. so the original is correct.

**Comment by petersilva** [comment]
oops... the colons are not optional however... the colons are mandatory... so the original isn't right.

**Comment by kaiwirt** [comment]
The way i read RFC3339 it is a subset of all the possible date / time formats from ISO 8601. According to the introduction (in my understanding) RFC3339 is one possible profile of ISO 8601 which is meant to improve consistency and interoperability.

In my point of view we should either update the time format to follow the SHOULD, or we should update the Spec to refer to ISO 8601 instead of RFC 3339

**Comment by petersilva** [comment]
fwiw, in python:

```
import datetime     # for general datetime object handling
import iso8601      # for date string -> date object

>>> input_string='1989-01-01T00:18:07-05:00'
>>> iso8601.parse_date(input_string)
datetime.datetime(1989, 1, 1, 0, 18, 7, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), '-05:00'))
>>>
>>> input_string='19890101T001807-0500'
>>> iso8601.parse_date(input_string)
datetime.datetime(1989, 1, 1, 0, 18, 7, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), '-05:00'))

```

The python library for parsing iso8601 dates considers it optional.

**Comment by petersilva** [comment]
amusing: https://ijmacd.github.io/rfc3339-iso8601/

**Comment by kaiwirt** [comment]
:-)))

**Comment by petersilva** [comment]
ok, actually read the standard now...  page 7.

" The following section defines a profile of ISO 8601 for use on the
   Internet.  It is a conformant subset of the ISO 8601 extended format.
   Simplicity is achieved by making most fields and punctuation
   mandatory."

ok yup. date should be changed to the "normal" one as shown in the examples.

**Comment by golfvert** [comment]
I have updated the text in the adoc file. Made a pull request.

**Comment by josusky** [comment]
I think this issue could be closed, I think there were multiple pull requests, e.g. https://github.com/wmo-im/wis2-notification-message/pull/18 not sure if there is anything else that needs to be changed.

**Comment by amilan17** [comment]
@tomkralidis can we close this issue?
