### ISSUE TITLE
clarify properties.content

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-notification-message#29]
(carryon from #26 from @antje-s)

7.1.7.5. Content
Perhaps adding something like: "The inline content filed is useful for warnings to avoid the extra step of downloading. But also for warnings the maximum size must not be exceeded"
Splitting of
"A WNM SHOULD provide a content property, consisting of an encoding property (fixed to either utf-8 or base64), a value
property (of less than 2048 bytes) of the data, as well as a size property with the length of the data."
--> to perhaps
A - "A WNM SHOULD provide a content property, consisting of an encoding property, a value property, and a size property"
B - "The content encoding property is fixed to either utf-8 or base64"
C - "The size of the content value SHALL be of less than 2048 bytes"

cc @kaiwirt @josusky @golfvert

**Comment by josusky** [comment]
We have lost somewhere `gzip`. It is also an allowed [encoding](https://github.com/wmo-im/wis2-notification-message/blob/main/schemas/notificationMessageGeoJSON.yaml) and it can significantly help to fit CAP and other XML-based messages into the 2048 bytes limit.

**Comment by tomkralidis** [comment]
@josusky gzip is an acceptable encoding (along with `base64` and `utf-8`).

**Comment by amilan17** [comment]
Is this related to #39

**Comment by tomkralidis** [comment]
Closing this one given gzip is back in the specification.
