### ISSUE TITLE
problems with GeoJSON vertical coordinates

### ISSUE THREAD

**Issue by mo-marqh** [wmo-im/wis2-notification-message#32]
within
https://github.com/wmo-im/wis2-notification-message/blob/main/standard/sections/clause_7_normative_text.adoc#geometry

there is an example that uses a geometry point with an elevation value

We have had significant issues with the GeoJSON specification with respect to vertical coordinates
These are really problematic in detail
my organisation have recommended no use of vertical coordinates in any GeoJSON payloads due to these issue

It would be good to understand the desire or use of vertical position within the message payloads and to consider recommending against the use of 3D coordinates, limiting use to 2D position only, to avoid this problematic area

Context:

(RFC 7946: The GeoJSON Format (rfc-editor.org) https://www.rfc-editor.org/rfc/rfc7946)
```
   The coordinate reference system for all GeoJSON coordinates is a
   geographic coordinate reference system, using the World Geodetic
   System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units
   of decimal degrees.  This is equivalent to the coordinate reference
   system identified by the Open Geospatial Consortium (OGC) URN
   urn:ogc:def:crs:OGC::CRS84.  An OPTIONAL third-position element SHALL
   be the height in meters above or below the WGS 84 reference
   ellipsoid.  In the absence of elevation values, applications
   sensitive to height or depth SHOULD interpret positions as being at
   local ground or sea level.
```

This clearly states that all heights are in metres and with respect to the WGS84 datum reference ellipsoid

The WGS84 ellipsoid is quite divergent from measured mean sea level as standardised by regional and local mapping organisations, especially at higher mid-latitudes

for example,
At 50.2° of latitude the delta between WGS84 and mean sea level is 53.4 metres
using (50.218 -5.327) as a sample location UK

So, it seems to me that any height provided within a GeoJSON payload is almost certainly not what might be expected (by the standard), as local altitude above standardised mean sea level is almost always used by data creators and the standard specifies that this needs to be adjusted to a height with respect to WGS84 (a non-trivial calculation).

But, lots of data providers likely don't know this nor understand that there are location dependent significant deviations, and so may well assume that elevation means altitude above mean sea level and provide the perceived useful number, but not to the standard.

So, as a data consumer, do i code to the spec? do i second guess based on assumptions of common usage?

An ~50 metre height difference is really significant, especially for use in aviation, sea level monitoring, ... etc.

There is an internationally standardised vertical datum built for exactly this purpose: EGM2008
but GeoJSON does not recognise EGM nor anything similar, it just references the WGS84 parameterised oblate spheroid, which is quite divergent from mean sea level.

(this has been shared with the GeoJSON community, but no resolution has been progressed)

**Comment by tomkralidis** [comment]
TT-WISMD 2023-09-11
- elevation is not required for emitting geometry
- if an organization is unsure/skeptical about an elevation's value/semantic in WNM, they are free to specify only x and y coordinates, and/or specify their own elevation value by extending WNM
- this would also be valuable to qualify in WCMP2

Specification updates:
- a WNM geometry MAY provide a third element (height) as per clause 4 of the GeoJSON specification
