### ISSUE TITLE
data_id and topic hierarchy question

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-notification-message#33]
I'd like to understand why the Topic\_Hierarchy path is bundled with the unique id of the data. This seems to violate the separation of concerns concepts...

**Comment by antje-s** [comment]
From my point of view it is important to distinguish that the topic-hierarchy is not dependent on an instance-id, the topic-hierarchy-value is only used and combined with an instance-id in the data-id value. Since the concrete message (with this data-id) is then published under that topic, only something is used that is already connected anyway

**Comment by petersilva** [comment]
> I'd like to understand why the Topic_Hierarchy path is bundled with the unique id of the data. This seems to violate the separation of concerns concepts...

perhaps I don't understand the concept.  I went to wikipedia:

> "separation of concerns is a design principle for separating a [computer program](https://en.wikipedia.org/wiki/Computer_program) into distinct sections. Each section addresses a separate [concern](https://en.wikipedia.org/wiki/Concern_(computer_science)), a set of information that affects the code of a computer program."

A "unique id of the data" that applies across all data sets is actually a violation of the separation of concerns, from photographs of weather observation stations, to radar volume scans, to numerical weather outputs.  Having an id that need only be unique within a topic hierarchy actually implements separation of concerns, previding a per topic namespace. Id's in one topic never collide with id's in another.  One can use much shorter id's if the id's are hierarchically separated.  The entire purpose of the topic hierarchy is the separation of the data into categories of interest... 

I might be help if you could explain why you see this as a violation of this principle?
