### ISSUE TITLE
make temporal description a permission

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-notification-message#34]
As per https://wmo-im.github.io/wis2-notification-message/standard/wis2-notification-message-DRAFT.html#_temporal_description_datetime_start_datetime_end_datetime, Requirement 8A states:

> A WNM SHALL provide a temporal description by either a properties.datetime property or both the properties.start_datetime and properties.end_datetime properties.

This may prove problematic for publishers who do not have this information apriori (similar to `geometry`, which allows for `null`).

Proposing to relax this requirement to a permission (MAY).  Thoughts?

**Comment by josusky** [comment]
Yes, it is probably better to relax the requirement than to force (some) people to set there a bogus date.

**Comment by McDonald-Ian** [comment]
Whilst some people might set a bogus date if one SHALL be supplied, is it possible that a data originator would now choose not to set the properties where such data is available and meaningful?

I would lean towards a qualified SHALL, such that if the data is available and meaningful it would be supplied, but if there is no data the properties can be left null, signifying there either is no data, or it would be meaningless. This appears to be similar to the qualification around geometry.

Your thoughts?

Best Wishes

--
ian

**Comment by tomkralidis** [comment]
TT-WISMD 2023-03-08:
- if user cannot generate temporal information, then they SHALL emit `properties.datetime=null`
