### ISSUE TITLE
Decide encoding of integrity value

### ISSUE THREAD

**Issue by kaiwirt** [wmo-im/wis2-notification-message#39]
We need to decide the encoding of the integrity value in notification messages. Currently there are messages which encode the integrity value as ASCII representation of the hex value. Others, which encode the integrity as Base64.

Option 1: Encode integrity as ASCII hex
Option 2: Encode integrity as Base64
Option 3: Allow both and add a field integrity.encoding to the message.

**Comment by josusky** [comment]
OK, let me repeat my main arguments from the previous discussion.
I agree that for some testing purposes, it is useful to be able to use CLI tools to generate a hash but there are ways how to convert it, e.g. like this `sha256sum test.data | xxd -r -p | base64`. For the reverse conversion, you can use `echo "<base64-value>" | base64 -d | hexdump -e '"%02X"'`
However, for day-to-day operations, we will all use higher-level tools not just `bash` :-)
Any decent programming language has a base64 encoding/decoding functionality, in fact, **we already use base64 encoding for the "content" field**. So we are not adding an additional dependency here. To sum it up, pros of base64 for integrity value:
1. One way of encoding all (both) binary data fields in the notification.
2. Shorter.
3. Backward compatible with v03.

Cons:
1. Less comfortable for CLI.

**Comment by josusky** [comment]
And maybe one more thing, currently both encodings are used and the software can cope with it without explicit `integrity.encoding` property. But in general, I vote for the "Option 2" :-)

**Comment by golfvert** [comment]
If we can avoid creating yet another choice and go for a single option, that would be good.
Considering that we already agreed on base64 for encoding the content, I'd go too for option 2.
If it is agreed, we can ask ET-Metadata where this is maintained, to make that choice explicit.

**Comment by kaiwirt** [comment]
We also implemented Option 2.
