### ISSUE TITLE
consider importing old issues from GTStoWIS2 for information purposes

### ISSUE THREAD

**Issue by petersilva** [wmo-im/wis2-notification-message#4]
the early work of tt-protocols provides some background that may be of interest to those working on mqp in future:

https://github.com/wmo-im/GTStoWIS2/issues/68

https://github.com/wmo-im/GTStoWIS2/issues/31

https://github.com/wmo-im/GTStoWIS2/issues/30

https://github.com/wmo-im/GTStoWIS2/issues/25

https://github.com/wmo-im/GTStoWIS2/issues/36

**Comment by amilan17** [comment]
@tomkralidis can we close this?
