### ISSUE TITLE
remove topic hierarchy from data_id

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-notification-message#43]
As discussed at the Meeting-2023-05-05, we decided to remove the topic hierarchy as a requirement in the data_id property and remove it from the example

**Comment by tomkralidis** [comment]
PR in #45

**Comment by tomkralidis** [comment]
TT-WISMD 2023-05-22:
- data_id: update schema and normative text to explain that producers SHOULD NOT use an opaque id, but something meaningful to support client side filtering

**Comment by tomkralidis** [comment]
TT-WISMD 2023-09-11:
- transform requirement 7C leftover from #45 into a permission

**Comment by tomkralidis** [comment]
PR in #61
