### ISSUE TITLE
provide ETS/reference implementation

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-notification-message#57]
We need a reference implementation of WNM which would have the following features:

1. encoding
2. decoding
3. validation
4. executable test suite against the normative abstract test suite

We've been working on [pywis-pubsub](https://github.com/wmo-im/pywis-pubsub) which provides this capability and already covers items 1-3 above.

We need to add capability to pywis-pubsub that implements the ATS as an ETS.  Example workflow:

```bash
pywis-pubsub ets validate https://example.org/path/to/wnm-example.json
```

**Comment by tomkralidis** [comment]
TT-WISMD 2023-09-11:
- ETS is valuable/not critical path for INFCOM-3
- can implement following adoption at INFCOM-3

**Comment by tomkralidis** [comment]
PR in https://github.com/wmo-im/pywis-pubsub/pull/37

**Comment by tomkralidis** [comment]
TT-WISMD 2023-09-25
- @antje-s / @josusky to test / validate / provide feedback

**Comment by antje-s** [comment]
pywis-pubsub ets validate my-notification_example
works fine.
Maybe the response of the validation against the schema could be made more detailed to have a hint where the validation failed in case of errors.
The 4 example files under "examples" have passed the validation check  ;-)

**Comment by tomkralidis** [comment]
Thanks for the feedback @antje-s.  FYI a PR can be found in https://github.com/wmo-im/pywis-pubsub/pull/39 to provide better diagnostics on schema errors.
