### ISSUE TITLE
clarify metadata_id

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-notification-message#64]
https://wmo-im.github.io/wis2-notification-message/standard/wis2-notification-message-DRAFT.html#_properties_2

Make it clear that `metadata_id` refers to the associated WCMP2 identifier

**Comment by josusky** [comment]
To me the text in WNM seems clear, but perhaps we can add there an explicit reference to WCMP2 `/req/core/identifier`, that is to the `id` property of metadata records?

**Comment by tomkralidis** [comment]
TT-WISMD 2023-09-25
- provide reference to WCMP2 `/req/core/identifier`
- so WNM `properties.metadata_id` = WCMP2 `id`
  - SHOULD be from GDC
- add permission:
  - for links to non-WIS2 GDC metadata catalogues, add a link relation `rel=related` or `rel=parent`

**Comment by SimonElliottEUM** [comment]
As a non-expert reader, it was not clear to me how to populate the metdata_id by looking at 7.1.10 of the draft WMO WIS2 Notification Message Encoding document. The additional input suggest above would address that concern.

**Comment by gaubert** [comment]
@tomkralidis @josusky sorry could not make it to the meeting yesterday. 
Sounds fine to me as well with the reference to the WCMP2 id.
