### ISSUE TITLE
Custom link relation types do not resolve

### ISSUE THREAD

**Issue by 6a6d74** [wmo-im/wis2-notification-message#72]
The custom link relation types specified in the WIS2 Notification Message specification don't resolve to useful resources. They need to be added to relevant WMO vocab resource.

Examples:
* http://def.wmo.int/def/rel/wnm/-/update
* http://def.wmo.int/def/rel/wnm/-/deletion

**Comment by tomkralidis** [comment]
FYI these values are managed in the [WCMP2 codelists](https://github.com/wmo-im/wcmp2-codelists/blob/main/codelists/link-type.csv), which will be published to codes.wmo.int accordingly (we would have to determine whether def.wmo.int could be put forth or whether we need to update the URLs proper).

**Comment by amilan17** [comment]
I think we can close this issue as we are now pointing to the WMO Codes Registry
