### ISSUE TITLE
be more specific on properties.data_id

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-notification-message#81]
It appears as if most organizations providing notifications to WIS2 are putting forth `properties.data_id` with the following convention:

`WIS2 topic - origin/a + unique id`

Example:

- message published:
  - topic; `origin/a/wis2/mar/casablanca_met_centre/data/core/weather/surface-based-observations/synop`
  - message `properties.data-id`: `wis2/mar/casablanca_met_centre/data/core/weather/surface-based-observations/synop/WIGOS_0-20000-0-60340_20240123T010000`

Do we want to provide more weight given the above (SHALL/SHOULD)?  Do we have to (is topic + unique_id unique and meaningful enough)?

**Comment by josusky** [comment]
It is convenient for current WIS2 nodes to use the same string, kind of a relative path or prefix, in the topic and the `data_id`. But duplicity is a sign of bad design (yes, I am a software developer). If we made it a rule then we could as well drop this "prefix" from the `data_id` (because it would be deducible from the topic).
On the other hand, we should take into account that we are in an early stage and data providers are not very diverse yet. Therefore I suggest keeping it open, to give more possibilities to the data providers.

**Comment by kaiwirt** [comment]
I agree with @josusky . In my opinion the only purpose of the data_id is to uniquely identify a piece of data. That said i would not specify much more as it being unique and printable characters.

If we want to use the data_id for more than just to identify the data, we would also need to specify the intended usages along with the intended format of the data_id

**Comment by gaubert** [comment]
I also agree with @josusky and @kaiwirt. I have followed what Simon defined for the data_id but it doesn't make much sense to add the topic to make it unique. For EUMETSAT, the data id is unique with the part at the end.
I have another question related: Would it make sense to the a property containing the topic where the message has been published ? It could make sense for tracability purposes. 
What are your views ?

**Comment by josusky** [comment]
@gaubert The topic is available to the MQTT client upon reception of the message/notification. Sure, this is protocol specific, i.e. if one day we migrate to other pub-sub protocol, the extraction of topic would be part of the code that will need to be changed. On the other hand, adding it into the notification would be protocol agnostic, but at the same time a duplicity that could lead to errors - some one could publish to topic A a notification claiming to be in the topic B.

**Comment by golfvert** [comment]
In the interest of simplicity (being more prescriptive on how to have a unique data_id does not provide additional value), it is decided to keep the specification as they are. Issue to be closed.

**Comment by tomkralidis** [comment]
Thanks for the verifications (also see discussion in #43).  Closing.
