### ISSUE TITLE
Normalization of WNM references to artifacts such as schemas, codes...

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-notification-message#83]
Ensure consistency of WNM URLs and resources outside of the Manual on WIS. Below are lists of what exists today in WNM

* The normative provisions in this Standard are denoted by the URI:
   * http://wis.wmo.int/spec/wnm/1

* Examples provided in this specification are encoded as GeoJSON. Complete examples can be found at 
  * https://schemas.wmo.int/wnm/1.0/examples
 
* The WIS2 Notification Message schema can be found at 
   * https://schemas.wmo.int/wnm/1.0/notificationMessageGeoJSON.yaml

* Requirements Class
  * http://www.wmo.int/spec/wnm/1/req/core

* "rel" codes
   * http://def.wmo.int/def/rel/wnm/-/update
   * http://def.wmo.int/def/rel/wnm/-/deletion

* Examples and relevant guidance will be posted to 
  * https://community.wmo.int/en/activity-areas/wis/wnm. 

* Browseable and searchable code tables can be found at 
  * https://codes.wmo.int/...

**Comment by amilan17** [comment]
**Community page:** 
* https://community.wmo.int/en/activity-areas/wis/wis2-notification-message

**Codes registry**
_always the latest approved version of codes (no versioning embedded into URLs)_
* http://codes.wmo.int/wis/link-relations

**Schemas site:** 
* validation: https://schemas.wmo.int/wnm/1.0/notificationMessageGeoJSON.yaml
* ATS: https://schemas.wmo.int/wnm/1.0/ats
* examples: https://schemas.wmo.int/wnm/1.0/examples

**Spec namespace**
* http://wis.wmo.int/spec/wth/1
* Options
    * a) create a simple landing page for this with text explaining that this is the namespace only
    * b) do not [hot link](http://wis.wmo.int/spec/wth/1) the URI in the publication
    * c) Do not put full URLs in to /spec/* in the conformance class

**Comment by amilan17** [comment]
As discussed with Tom, the plan is to publish to schemas.wmo.int like this: 

**Schemas site:**
- https://schemas.wmo.int/wnm/1.0/
  -    standard
       -  PDF (from GH tag release)
  -    examples (maybe)
  -    kpis (once available)
  -    shemas
  -    wnm.zip (GH tag release, includes everything including examples)

http://www.wmo.int/spec/.... --> this will change to wis.wmo.int/...

Update update URLs as needed

**Comment by tomkralidis** [comment]
- PR in #92 
- Release process updated in https://github.com/wmo-im/wis2-notification-message/wiki/ReleaseProcess

**Comment by tomkralidis** [comment]
- PR in #92
- Release process updated in https://github.com/wmo-im/wis2-notification-message/wiki/ReleaseProcess
