### ISSUE TITLE
Duplication of REQs

### ISSUE THREAD

**Issue by antje-s** [wmo-im/wis2-notification-message#89]
- 7.1.3 GeoJSON compliance REQ2 B(part)+C and 7.1.6 Type REQ5 A+B
- 7.1.3 GeoJSON compliance REQ2 B and 7.1.5 Version REQ4 A
- 7.1.3 GeoJSON compliance REQ2 B and 7.1.7 Geometry REQ6 A
- 7.1.3 GeoJSON compliance REQ2 B and 7.1.4 Identifier REQ3 A

Could we remove part A of the REQs as duplicates of 7.1.3. GeoJSON compliance REQ2? Perhaps adding a link to 7.1.3 GeoJSON section.

**Comment by amilan17** [comment]
@antje-s - I like your suggestion. 
@tomkralidis - what do you think?

**Comment by tomkralidis** [comment]
PR in #93.
