### ISSUE TITLE
Should the message include (optionally) the size of the data announced by this message

### ISSUE THREAD

**Issue by golfvert** [wmo-im/wis2-notification-message#9]
In the latest version, the "size" of the data to be downloaded (if it is downloadable data - so no API), is not included in the message.
Shall we make it an acceptable but optional information?

**Comment by kaiwirt** [comment]
I think size is a useful information. Some users might want to download data only up to a given size limit.

It might also be helpful for caches to have size information beforehand.

**Comment by tomkralidis** [comment]
This is now available via the `links.*.length` property. See Recommendation 3B in https://wmo-im.github.io/wis2-notification-message/standard/wis2-notification-message-DRAFT.html#_links
