### ISSUE TITLE
pubtime clarity

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-notification-message#97]
Introductory sentence: 
"The pubtime property identifies the date/time when the notification was first posted or published by the originator."

Recommendation 2 | /rec/core/pubtime
-- | --
A | "For notifications of updates or deletions, the properties.pubtime property SHOULD be updated in support of client handling of change detection."

@david-i-berry review: If the pubtime is updated, is it a new notification? If it is the same notification, how does this relate to the opening sentence?

**Comment by amilan17** [comment]
@tomkralidis @wmo-im/tt-wismd

**Comment by josusky** [comment]
The `pubtime` shall not be changed. The notification about an updated version of a data set or about deleted metatada record is a new notification. So for clarity I would propose following formulation:
"Notifications about updates or deletions of datasets or metadata are new notifications and therefore their `properties.pubtime` property is naturally different than that of the notification about the initial creation."
